### ISSUE TITLE
cant see what sessions are saved beause of font colour

### ISSUE THREAD

**Issue by zayd62** [sienori/Tab-Session-Manager#377]
I saved a session and when i go to view the session, the text is light gray on white background so i cant see what the text actually says 

![image](https://user-images.githubusercontent.com/26032382/52208479-bb980700-2878-11e9-994a-79eb10c4f36b.png)

**Comment by sienori** [comment]
I fixed it. https://github.com/sienori/Tab-Session-Manager/commit/d6197a98376b9f79a493a80bf569646d9eb82eda
Thank you for the report!

**Comment by LandisTwo** [comment]
it is not fixed.
I am using version 4.5.2 and I still have this issue. 
I can Not see the menu items eg, 'replace session with current window'

**Comment by qlixed** [comment]
Same issue here, hard to see, is probably a good idea to integrate a dark theme to use when firefox is in using one

**Comment by sienori** [comment]
This issue is solved in version 5.2.0.
