### ISSUE TITLE
Tab Session Manager works only if i manually click 'save'

### ISSUE THREAD

**Issue by WPFilmmaker** [sienori/Tab-Session-Manager#629]
## Short description

Tab Session Manager works only if i manually click 'save'. It does not save every 15min as I set and it does not safe once the browser is closed as I set. In the past I had an infamous bug no session being shown but I never bothered to fix it. 

I was then able to save a session by clicking 'save' but now I see thats the only way I can make TSM save things. If you can let me know more ways in which I can provide more info I would be glad to do so.

## Platform information
* Platform (OS): Lubuntu 18.04
* Version of browser: 81.0 (64-bit)
* Version of Tab Session Manager: Version 6.2.1

**Comment by papi3r** [comment]
I have the same issue. Commenting to add context.

## Platform information
* Platform (OS): macOS 10.14.6
* Version of browser: 79.0 (64-bit)
* Version of Tab Session Manager: Version 6.2.1

## Additional context
I have turned on add-on debugging, I can see errors related  to `background.js`:

```
10:11:51.142 [info] background/autoSave: setUpdateTempTimer() background.js:1:71229
10:11:51.180 [info] background/autoSave: handleTabUpdated() background.js:1:71229
10:11:51.180 [info] background/autoSave: setUpdateTempTimer() background.js:1:71229
10:11:52.684 [debug] background/autoSave: updateTemp() background.js:1:71229
10:11:52.686 [debug] background/save: loadCurrentSession() Toolbox - Extension / Tab Session Manager 
Array [ "temp" ]
 default background.js:1:71229
10:11:52.697 [debug] background/ignoreUrls: ignoreUrls() 
Object { windows: {…}, windowsNumber: 1, windowsInfo: {…}, tabsNumber: 19, name: "Toolbox - Extension / Tab Session Manager", date: 1601917912687, lastEditedTime: 1601917912687, tag: (1) […], sessionStartTime: 1601914779738, id: "6d33cdf2-b5be-476f-a809-36db3e999b44" }
 
Array [ "", "moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/popup/index.html*" ]
background.js:1:71229
10:11:52.700 [debug] background/ignoreUrls: => ignoreUrls() 
Object { windows: {…}, windowsNumber: 1, windowsInfo: {…}, tabsNumber: 19, name: "Toolbox - Extension / Tab Session Manager", date: 1601917912687, lastEditedTime: 1601917912687, tag: (1) […], sessionStartTime: 1601914779738, id: "6d33cdf2-b5be-476f-a809-36db3e999b44" }
background.js:1:71229
10:11:52.701 [debug] background/tag: getSessionsByTag() temp null background.js:1:71229
10:11:52.701 [debug] background/sessions: getAll() null background.js:1:71229
10:11:53.141
[error] background/sessions: getAll() 
error { target: IDBRequest, isTrusted: true, srcElement: IDBRequest, currentTarget: IDBRequest, eventPhase: 2, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
background.js:1:71229
10:11:53.142
[error] background/autoSave: updateTemp() TypeError: n is undefined
    J moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/background/background.js:29
    pe moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/background/background.js:29
    Me moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/background/background.js:29
    ge moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/background/background.js:29
background.js:1:71229
10:11:54.612 [info] background/autoSave: handleTabUpdated() background.js:1:71229
10:11:54.612 [info] background/autoSave: setUpdateTempTimer() background.js:1:71229
10:11:55.041 [info] background/autoSave: handleTabUpdated() background.js:1:71229
10:11:55.042 [info] background/autoSave: setUpdateTempTimer() background.js:1:71229
10:11:55.732 [info] background/autoSave: handleTabUpdated() background.js:1:71229
10:11:55.733 [info] background/autoSave: setUpdateTempTimer() background.js:1:71229
10:11:57.238 [debug] background/autoSave: updateTemp() background.js:1:71229
10:11:57.246 [debug] background/save: loadCurrentSession() Toolbox - Extension / Tab Session Manager 
Array [ "temp" ]
 default background.js:1:71229
10:11:57.262 [debug] background/ignoreUrls: ignoreUrls() 
Object { windows: {…}, windowsNumber: 1, windowsInfo: {…}, tabsNumber: 19, name: "Toolbox - Extension / Tab Session Manager", date: 1601917917247, lastEditedTime: 1601917917248, tag: (1) […], sessionStartTime: 1601914779738, id: "621b9d6e-4feb-4736-ad7c-33f2bcd4f3bf" }
 
Array [ "", "moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/popup/index.html*" ]
background.js:1:71229
10:11:57.264 [debug] background/ignoreUrls: => ignoreUrls() 
Object { windows: {…}, windowsNumber: 1, windowsInfo: {…}, tabsNumber: 19, name: "Toolbox - Extension / Tab Session Manager", date: 1601917917247, lastEditedTime: 1601917917248, tag: (1) […], sessionStartTime: 1601914779738, id: "621b9d6e-4feb-4736-ad7c-33f2bcd4f3bf" }
background.js:1:71229
10:11:57.265 [debug] background/tag: getSessionsByTag() temp null background.js:1:71229
10:11:57.265 [debug] background/sessions: getAll() null background.js:1:71229
10:11:57.519
[error] background/sessions: getAll() 
error { target: IDBRequest, isTrusted: true, srcElement: IDBRequest, currentTarget: IDBRequest, eventPhase: 2, bubbles: true, cancelable: true, returnValue: true, defaultPrevented: false, composed: false, … }
background.js:1:71229
10:11:57.520
[error] background/autoSave: updateTemp() TypeError: n is undefined
    J moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/background/background.js:29
    pe moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/background/background.js:29
    Me moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/background/background.js:29
    ge moz-extension://c2cae340-43fb-2440-8d8d-895eed89ea6b/background/background.js:29
background.js:1:71229
```

**Comment by WPFilmmaker** [comment]
@papi3r I also want to add that I noticed that by using this method to save, TSM only saves 1 session, so if I have an old one, save a new one it shows as 2 but once FF is restarted TSM shows only the newer session, so it overwrites the first one.

**Comment by WPFilmmaker** [comment]
on my side FF 82.0.2 (64-bit) and Version 6.3.0 the issue is fixed. @papi3r unless you object for me this ticket can be closed.
@sienori thanks!

**Comment by electric-skeptic** [comment]
I still have this issue, with Firefox and TSM both up to date, although the computer right beside me does not! ARRGH!

**Comment by sienori** [comment]
@WPFilmmaker
The cause is unknown, but reloading the extension seems to have solved the problem. I close this issue.

@papi3r 
Getting the session seems to have failed. You should not be able to see the list of saved sessions. Please try reinstalling TSM or [repairing IndexedDB](https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error).

@electric-skeptic 
Discuss here: https://github.com/sienori/Tab-Session-Manager/issues/651
