### ISSUE TITLE
Silently not importint Session Manager saves

### ISSUE THREAD

**Issue by Bgs4269** [sienori/Tab-Session-Manager#64]
I just upgraded from FF56 to FF58b3 and switched from Session Manager to Tab Session Manager because of the lack of support for the former and the supposed ability to import.

When I try to import and select my last .session file, nothing happens. Not error messages. No tabs loaded.

OS is OSX 10.12.6.

**Comment by Bgs4269** [comment]
The session is not encrypted.

**Comment by mr-brunes** [comment]
It says "Session Imported" on TSM 1.5.0 on FF 57.0 (64 bit) on Win10 but otherwise it's as OP says i.e. nothing happens.

**Comment by sienori** [comment]
That .session file may be different from my assumed structure.
If possible, please upload the .session file for debugging. (Please be careful about privacy)

@mr-brunes 
If the session duplicates an existing one, it will not be imported.

**Comment by xvazquezc** [comment]
Same problem in Ubuntu, with FF57(64bit) + TSM 1.5.0 and clean installation

**Comment by TillSchmi** [comment]
Hi there, I encounter the same issue. 
General structure of former backup.session file seems to be fine (as far as I can judge). 
Since being comma separated, could it be the backup.session is just too long?
Just took the first couple of entries for generic test; tried with short ones (~250kB) which worked seamlessly. But importing a ~13MB backup.session failed eventually; same for ~6MB

**Comment by Bgs4269** [comment]
Mine is also around 3.5MB. This could be related to size after all.

**Comment by mr-brunes** [comment]
My .session file failures are around 5MB.

**Comment by xvazquezc** [comment]
Got a 327.5 kB sesion loaded right away. Failed with one of 750.2 kB.

**Comment by sienori** [comment]
Probably I fixed it in version 1.8.0.
Try it.
https://github.com/sienori/Tab-Session-Manager/commit/190a013e268bd774786ce54ffdde998f5cdc2892
https://github.com/sienori/Tab-Session-Manager/commit/c566d11e31c1f91b490d4aaf7a0dc52986668e93

**Comment by xvazquezc** [comment]
@sienori sorry for replying to a closed thread.
I just got back to the office and being able to check on this.
Still not working with TSM 1.9.2.
Has it being solved to anybody?
