### ISSUE TITLE
I have to login every time I restart my PC

### ISSUE THREAD

**Issue by jaepil-choi** [sienori/Tab-Session-Manager#752]
## Short description

Unlike other Chrome extensions, Taab Session Manager doesn't keep me logged in. 

## Steps to reproduce

1. Start browser with clean profile
2. Install Tab Session Manager
3. Enable cloud sync and login to Google. 
4. Restart the PC and get the login window from Tab Session Manager. 

## Expected result

Like other extensions, TSM should keep me logged in. 

## Actual result

TSM signs me out when I restart the PC. 

## Platform information
* Platform (OS): Win 10
* Version of browser: Chrome Version 90.0.4430.85 (Official Build) (64-bit)
* Version of Tab Session Manager: The latest 6.6.0

## Additional context

My Chrome is always logged in to my account and I have many Chrome-related startup programs like Google Drive. 
Since all other Google login required extensions like Evernote keeps me logged in as expected, TSM's behavior seems like a bug.

**Comment by neoOpus** [comment]
same here it keeps asking for login to google even during browsing sessions and after it has already been connected to google (which should be done once for all or every 30 days)

**Comment by xHurricanex** [comment]
Same for me

**Comment by sienori** [comment]
I'll investigate it. #701

**Comment by sienori** [comment]
I have fixed the problem of the login screen appearing every time. https://github.com/sienori/Tab-Session-Manager/commit/641e4db90a38aab62ddfac60a9959710135d92d6
It will be enabled in the next update.

**Comment by jaepil-choi** [comment]
@sienori , 

Seems like the issue has not been resolved. I'm on ver 6.7.0 and the issue persists.

**Comment by xHurricanex** [comment]
The same for me (very strange) - have just booted my PC and was asked to log in Google again...

**Comment by sienori** [comment]
Signing out and signing in again in the settings page may solve the problem.

If you are using Chrome on two or more devices, the first Chrome you sign in to will fix the problem.
The second Chrome you sign in with will still have the problem.

**Comment by xHurricanex** [comment]
Looks like the problem is tricky.
Today 10 minutes after the first manual sign-off-sign-in I rebooted PC - and TSM still works fine.
So maybe now the problem is if you are not signed in for some period of time.
For example, if you turn off PC at night (because you sleep) these 7-8 hours is enough for TSM to "forget" about Google and require you to sign in again in this case.

I have at least one more Google extension with the same trouble - Magical (https://chrome.google.com/webstore/detail/magical-%E2%80%93-text-expansion/iibninhmiggehlcdolcilmhacighjamp).
Yes, maybe that's Google who changed authorization rules again without warning.
But we have to be sure that TSM is working as it should be.

**Comment by jaepil-choi** [comment]
@sienori , could you reopen this issue since the issue has not yet been resolved?

**Comment by clipcarl** [comment]
Problem still exists for me.

**Comment by cocoonkid** [comment]
Same problem here. Happy I'm not alone :)

**Comment by dimanish** [comment]
Hello, just want to mention that I have the same issue, both on latest versions of Chrome and Microsoft Edge browsers while latest Firefox stable build works fine and no need to relogin each time after I click synchronization. I've signed out from account and login back but issue is still reproducible.

**Comment by jucor** [comment]
Same problem on TSM v6.8.2, Chrome Version 91.0.4472.77 (Official Build) (64-bit), Windows 10: TSM asks me to re-log into my @gmail.com account at most cloud sync. Maybe some of the cloud sync happen smoothy in the back, but I don't notice them. I definitely notice when it's broken and I need to click manually and log in, which seems to be every time, even without restartingthe PC or the browser.
Thanks @sienori  for an awesome extension, this would fix the last (annoying niggle) :)

**Comment by Archer36** [comment]
Same issue here on multiple Mac's running chrome 91.0.4472.77 with TSM version 6.8.3. Also having the issue on a Windows 10 laptop running TSM version 6.8.3

**Comment by Noiden** [comment]
Any update on this? I have the same issue.
Web browser: Brave 1.29.64 (Chromium 92.0.4515.159) beta (64-bit)
TSM version: 6.10.0

**Comment by SouzaRM** [comment]
> 
> 
> Any update on this? I have the same issue.
> Web browser: Brave 1.29.64 (Chromium 92.0.4515.159) beta (64-bit)
> TSM version: 6.10.0

Me too.
And it only occurs in ChroMe.
In Firefox no.

I have two-phase authentication, so it gets very complicated.

**Comment by renanbguedes** [comment]
Browser: Edge, Version 92.0.902.78 (Official build) (64-bit)
TSM Version: 6.10.0

I switched to Edge recently from Firefox and I'm experiencing this issue since then.

Thanks for this awesome extension, @sienori! I hope I can afford becoming a Patron soon. :)

**Comment by hexadecagram** [comment]
> Signing out and signing in again in the settings page may solve the problem.
> 
> If you are using Chrome on two or more devices, the first Chrome you sign in to will fix the problem.
> The second Chrome you sign in with will still have the problem.

I tried doing exactly as prescribed on MacOS 11 (was also experiencing this on Catalina up until a couple of weeks ago, when I finally upgraded), Tab Session Manager 6.10.0, Chrome 92.0.4515.159. I restarted my browser about 10 minutes ago and I was prompted yet again to login to Google.

You may want to look at how Tampermonkey accomplishes its synchronization. It does have an alternative called "Browser Sync" which has been working flawlessly for me for months. There may also be some clue as to how to get Google Sync to work in the code, but I don't use that mechanism myself.

**Comment by allenyllee** [comment]
The same here. Its annoying.
May I donate for solving this issue quickly?

**Comment by kesu1** [comment]
This issue only seems to be present in Chrome for me, not in Firefox.

**Comment by MrCaffeinated** [comment]
Present for me as well on 6.10.1 and Edge 93.0.961.44.

**Comment by amaisano** [comment]
I have Chrome on 3 Macs and 1 PC. The 3 Macs always keep my logged in to cloud sync. The PC "forgets" EVERY time I start the browser and the login for Google pops up (Windows 10).

**Comment by gitgit8** [comment]
Issue is still there, it is asking for me to login into my google every now and then even without restarting the browser or restarting the laptop.

I am using edge.

**Comment by jaepil-choi** [comment]
Dear @sienori , any update yet? Not sure if you're aware.

**Comment by Quantlyx** [comment]
For me the issue is still ongoing.
A fix would be really great!

**Comment by sienori** [comment]
@MrCaffeinated @gitgit8 @jaepil-choi 
As you pointed out, until version 6.11.0, it was not possible to keep logins on multiple devices.

But I found a way to fix this and released version 6.11.1! https://github.com/sienori/Tab-Session-Manager/commit/197a84ddd0e27ccb7d36c96466f69a7d575fcda8
I believe that this has completely solved this issue.

**Comment by gitgit8** [comment]
Can you please push these to both chrome and edge extension websties? They still have the old version
